### ISSUE TITLE
OTrP supporting status?

### ISSUE THREAD

**Issue by Kevin0626** [dthaler/teep#6]
> the (now obsolete) draft-ietf-teep-opentrustprotocol.

Hi, could you please clarify the above statement from the readme a bit? Does it mean the implementation in this repo for OTrP is obsolete or the OTrp version supported by this repo is obsolete (out-of-date?)?

**Comment by dthaler** [comment]
This repo contains partial implementations of two protocols.
1) draft-ietf-teep-opentrustprotocol.  This draft is now obsolete.
2) draft-ietf-teep-protocol.  This draft is not obsolete.

**Comment by Kevin0626** [comment]
Thank you! @dthaler 

I did a bit work tracing the status of these two specs. I guess following link refers to  the draft-ietf-teep-opentrustprotocol you mentioned - https://tools.ietf.org/html/draft-ietf-teep-opentrustprotocol-03

It looks the OTrP is a following work to the TEEP. I just wonder where the OTrP spec went? GP also defined some OTrP spec and what is the relationship with ietf spec?  Could you please share some info here？

**Comment by dthaler** [comment]
@Kevin0626 the OTrP spec was published by GlobalPlatform:
              https://globalplatform.org/specs-library/tee-management-framework-open-trust-protocol/
